-- ÀÎ±â¼ø.
SELECT S_NUM, STUDY_NAME, LOC, CATEGORY, IMG, RECRUITMENT, TO_CHAR(INPUT_DATE, 'YYYY/MM/DD') INPUT_DATE, NICK, USER_IMG
	FROM   (SELECT S.S_NUM, S.STUDY_NAME, S.LOC, S.CATEGORY, S.IMG, S.RECRUITMENT, S.INPUT_DATE, U.NICK, U.IMG USER_IMG, ROW_NUMBER() OVER( ORDER BY S.INPUT_DATE DESC) R_NUM
        	FROM FAV_STUDY FS, STUDY S, USER_TABLE U
    		WHERE ( FS.S_NUM = S.S_NUM ) AND ( S.ID=U.ID ) AND FS.ID = 'Dkfkfl'
    		)
   ORDER BY R_NUM ASC;

SELECT S_NUM, STUDY_NAME, LOC, CATEGORY, IMG, RECRUITMENT, INPUT_DATE, NICK, USER_IMG, cnt, R_NUM
FROM   (
			SELECT S.S_NUM, S.STUDY_NAME, S.LOC, S.CATEGORY, S.IMG, S.RECRUITMENT, S.INPUT_DATE, U.NICK, U.IMG USER_IMG, COUNT(FS1.S_NUM) cnt,
							ROW_NUMBER() OVER( ORDER BY COUNT(FS1.S_NUM) DESC, INPUT_DATE DESC) R_NUM
        	FROM STUDY S, FAV_STUDY FS1, USER_TABLE U
    		WHERE S.S_NUM = FS1.S_NUM(+) AND S.ID=U.ID AND ACCEPT_FLAG='Y' AND S.DEACTIVATION='N' AND DELETE_FLAG='N'
    		GROUP BY S.S_NUM, S.STUDY_NAME, S.LOC, S.CATEGORY, S.IMG, S.RECRUITMENT, S.INPUT_DATE, U.NICK, U.IMG
    		)
WHERE R_NUM BETWEEN 1 AND 20
ORDER BY R_NUM ASC;


select * from USER_TABLE;
select distinct s_num from  fav_study;
select * from fav_study where s_num='s_000041';
